language: c

before_install:
    - sudo apt-add-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes valac libglib2.0-dev

script:
    - valac --ccode --debug hello.vala
    - gcc $(pkg-config --cflags glib-2.0 gobject-2.0) -ftest-coverage -fprofile-arcs -o hello hello.c $(pkg-config --libs glib-2.0 gobject-2.0)
    - ./hello
    - gcov hello.vala

after_success:
    - bash <(curl -s https://codecov.io/bash)
